### ISSUE TITLE
Reported by clients: Kitchen knife can't kill some enemies

### ISSUE THREAD

**Issue by NeatWolf** [nyakowint/EverythingGoBoom-LC#29]
Hi, 
my players have been reporting a weird issue that doesn't make a lot of sense to me but they insist that it happens.
I'm not 100% sure depends on EverythingCanDie as well, but maybe you have an intuition about what can it be - if possible?

Everything works as intended, except since we recently got our hands on the Butler's knife.
Most vanilla and custom enemies seem to work but - I can't fully isolate the issue - there's a high rate of players saying they can't kill the Haunted Harpist ghost (https://thunderstore.io/c/lethal-company/p/Bob123/Haunted_Harpist/) with such knife since when we switched to EverythingCanDie (we were using another mod I can't remember at the moment).
The haunted ghost is the most reported, but not the only one.

Does that ring a bell or something? I'm a bit clueless on why the dagger or an enemy should work differently but maybe you have a better insight of the underlying tech aspect of it.

Or, maybe it's a collateral effect of some other mod. There's always that chance and isolating that is...complicated.

**Comment by Entity378** [comment]
sorry for the wait but at the moment I'm managing too many mods at the same time. It seems strange to me that the problem is this mod since it has no checks for the Butler's knife. If you can send me some clips with logs of when the problem occurs it would be appreciated, otherwise I can't solve the problem. Also check when the save is loaded to see if it loads all the configs correctly (if not it should give an error like this `[Error :EverythingCanDie] It was not possible to generate the configs for the enemy: ENEMYNAME`)
